#ifndef BONUSFUNCTOR_H
#define BONUSFUNCTOR_H

#include <QWidget>

namespace Ui {
class BonusFunctor;
}

/**
 * @brief The BonusFunctor class provides a QWidget-based panel
 *        with interactive controls to emit string operation requests.
 *
 * This widget emits signals for appending, chopping, or clearing strings,
 * and is intended to be used as a modular tool panel in a Qt application.
 */
class BonusFunctor : public QWidget {
    Q_OBJECT

public:
    /**
     * @brief Constructs the BonusFunctor widget.
     * @param parent The parent widget, if any.
     */
    explicit BonusFunctor(QWidget* parent = nullptr);

    /**
     * @brief Destructor.
     */
    ~BonusFunctor();

signals:
    /**
     * @brief Signal emitted to request appending a value.
     * @param value The QString to be appended.
     */
    void req_append(const QString& value);

    /**
     * @brief Signal emitted to request chopping the last character once.
     */
    void req_chop_once();

    /**
     * @brief Signal emitted to request clearing the current value.
     */
    void req_clear();

private:
    /**
     * @brief Sets up the internal panel UI and signal connections.
     */
    void setup_panel();

    /**
     * @brief Pointer to the UI elements generated by Qt Designer.
     */
    Ui::BonusFunctor* ui;
};

#endif // BONUSFUNCTOR_H
