#ifndef TIMELABELSETTINGS_H
#define TIMELABELSETTINGS_H

/**
 * @file timelabelsettings.h
 * @brief Declares the TimeLabelSettings widget used to configure the appearance of a time display label.
 */

#include <QWidget>
#include <QColor>
#include <QFont>

class QLabel;

namespace Ui {
/**
 * @brief Forward declaration of the UI class generated by Qt Designer for TimeLabelSettings.
 */
class TimeLabelSettings;
}

class DesktopMainWindow;

/**
 * @class TimeLabelSettings
 * @brief A widget for configuring time label appearance settings.
 *
 * Provides a UI interface for users to preview and apply settings like font and color
 * for the time display label on the desktop main window.
 */
class TimeLabelSettings : public QWidget {
    Q_OBJECT

public:
    /**
     * @brief Constructs a TimeLabelSettings widget.
     * @param parent Pointer to the parent DesktopMainWindow.
     */
    explicit TimeLabelSettings(DesktopMainWindow* parent = nullptr);

    /**
     * @brief Destroys the TimeLabelSettings widget.
     */
    ~TimeLabelSettings();

private:
    /**
     * @brief Pointer to the UI instance generated by Qt Designer.
     */
    Ui::TimeLabelSettings* ui;

    /**
     * @brief Pointer to the QLabel that displays the operating time.
     */
    QLabel* operatingTimeLabel;

    /**
     * @brief Structure to store font and color settings.
     */
    struct SettingsPack {
        QColor fontColor; ///< Font color of the time label.
        QFont font;       ///< Font of the time label.
    } settingsPack;

    /**
     * @brief Previews the current settings (font and color) on the label.
     */
    void process_preview();

    /**
     * @brief Applies the selected settings to the time label.
     */
    void process_apply();
};

#endif // TIMELABELSETTINGS_H
