#ifndef ENVIRONMENTWINDOW_H
#define ENVIRONMENTWINDOW_H

#include "AP3216CAdapterFactory.h"
#include <QMainWindow>

class QTimer;

QT_BEGIN_NAMESPACE
namespace Ui {
class EnvironmentWindow;
}
QT_END_NAMESPACE

/// @brief Device file path for the AP3216C sensor.
static constexpr const char* DEV_FILE = "/dev/ap3216c";

/// @class EnvironmentWindow
/// @brief Main window class to interface with the AP3216C environmental sensor.
class EnvironmentWindow : public QMainWindow {
	Q_OBJECT

public:
	/// @brief Constructor.
	/// @param parent Parent widget.
	EnvironmentWindow(QWidget* parent = nullptr);

	/// @brief Destructor.
	~EnvironmentWindow();

private:
	Ui::EnvironmentWindow* ui; ///< UI pointer generated by Qt Designer.
	AP3216CAdapterFactory factory; ///< Factory object for AP3216C sensor adapter.
	QTimer* period_request_timer { nullptr }; ///< Timer for periodic sensor data requests.

	/// @brief Setup memory-related resources or buffers.
	void setup_memory();

	/// @brief Setup UI elements.
	void setup_ui();

	/// @brief Process the data received from the sensor.
	/// @param data Sensor data structure.
	void process_data(const AP3216CData data);
};

#endif // ENVIRONMENTWINDOW_H
