/**
 * @class DinasourGameWindow
 * @brief Main window class for the dinosaur game UI and logic handling.
 */

#ifndef DINASOURGAMEWINDOW_H
#define DINASOURGAMEWINDOW_H

#include <QMainWindow>
class QPushButton;
QT_BEGIN_NAMESPACE
namespace Ui {
/**
 * @brief Forward declaration of the UI class generated by Qt Designer.
 */
class DinasourGameWindow;
}
QT_END_NAMESPACE

/**
 * @brief A QMainWindow-derived class managing the dinosaur game's main interface and events.
 */
class DinasourGameWindow : public QMainWindow {
    Q_OBJECT

public:
	/**
	 * @brief Constructor for DinasourGameWindow.
	 * @param parent Parent widget, default is nullptr.
	 */
	DinasourGameWindow(QWidget* parent = nullptr);

	/**
	 * @brief Destructor for DinasourGameWindow.
	 */
	~DinasourGameWindow();

private slots:
	/**
	 * @brief Slot called when the game ends to handle post-game logic.
	 */
	void process_gameend();

	/**
	 * @brief Slot called after the game starts to handle initialization.
	 */
	void post_game_start();

private:
	/**
	 * @brief Pointer to the UI object generated by Qt Designer.
	 */
	Ui::DinasourGameWindow* ui;

	/**
	 * @brief Flag indicating whether the game is paused.
	 */
	bool make_pause = false;

	/**
	 * @brief Pointer to the layup button in the UI.
	 */
	QPushButton* layup_btn;

	/**
	 * @brief Sets up signal-slot connections for UI interaction.
	 */
	void setup_connections();

	/**
	 * @brief Initializes and customizes UI elements.
	 */
	void setup_my_ui();
};
#endif // DINASOURGAMEWINDOW_H
